### ISSUE TITLE
如何獲取 Jlink OB 的固件

### ISSUE THREAD

**Issue by Linjieqiang** [KitSprout/JLink_ARM-OB#1]
你好，刚看到你的项目，我想问，打板以后如何获取得到Jlink OB的固件，我想使用072版本，带VCP的，可以作为虚拟串口使用。

**Comment by hom-wang** [comment]
可以參考 [this](http://akb77.com/g/stm32/jlink-ob/) and [this](http://www.amobbs.com/thread-5648404-1-1.html)

**Comment by Linjieqiang** [comment]
谢谢……

**Comment by Linjieqiang** [comment]
你好，我按照参考网站的东西，刷进去两个，但是不工作。请求确认下，是我的姿势不对吗？先刷0x8000000 后再刷 0x8004800 还是怎么样呢？

**Comment by hom-wang** [comment]
固件是直接從 amobbs 上獲取的，自己是將 dfu 固件轉成 hex 檔在燒錄進去，沒有試過另個網站的固件

**Comment by Linjieqiang** [comment]
能否把Hex固件转载到此处呢？我没有amobbs的帐号，万分感谢！

**Comment by Linjieqiang** [comment]
已注册阿莫BBS，顺利找到固件，准备烧录，谢谢分享！

**Comment by hom-wang** [comment]
如果還有問題的話可以再跟我說：）

**Comment by Linjieqiang** [comment]
好的，谢谢你。

**Comment by WZX0909** [comment]
固件能分享一下吗？

**Comment by hom-wang** [comment]
這裡不提供，麻煩自己從上面連結找
