### ISSUE TITLE
Are tTX and tRX j-link ob side's or target sides?

### ISSUE THREAD

**Issue by tomo0611** [KitSprout/JLink_ARM-OB#2]
I have a question.
I'm going to add J-Link OV to my circuit board, but idk tTX and tRX are J-Link side or Target side.

Which is correct?

tTX --- targetRX
tRX --- targetTX

tTX --- targetTX
tRX --- targetRX

**Comment by hom-wang** [comment]
![image](https://user-images.githubusercontent.com/4789358/72578093-f66f3f80-390f-11ea-9f34-762a23ca9093.png)
![image](https://user-images.githubusercontent.com/4789358/72578102-0424c500-3910-11ea-8351-6d09aad593b9.png)

tTX and tRX are J-Link side

**Comment by tomo0611** [comment]
Thank you very much(｡･ω･｡)ﾉ
